DELETE FROM Email_Sent;
DELETE FROM Email_Log;
DELETE FROM Works_At ;
DELETE FROM Registered_At ;
DELETE FROM Vaccinations ;
DELETE FROM Infections ;
DELETE FROM Has_Schedule ;
DELETE FROM Schedule ;
DELETE FROM MiddleSchools ;
DELETE FROM PrimarySchools ;
DELETE FROM HighSchools ;
DELETE FROM GeneralManagementFacilities ;
DELETE FROM HeadOfficeFacilities ;
DELETE FROM ManagementFacilities ;
DELETE FROM EducationalFacilities ;
DELETE FROM Operates ;
DELETE FROM Facilities ;
DELETE FROM Ministries ;
DELETE FROM Students ;
DELETE FROM Teachers ;
DELETE FROM Employees ;
DELETE FROM Persons ;
DELETE FROM Addresses_Facilities ;
DELETE FROM Addresses_Persons ;
