<!DOCTYPE html>
<html>
<body>
<br>
<hr>
<br>
<a href="./index.php">Homepage</a>
<h2>Main Project - Group kdc353_1</h2>
<br>
<br>

<h3>1-</h3>

<h3>2-</h3>
<a href="/student">CRUD Operations on Students</a><br><br>
<form action="display-students.php">
<input type="submit" value="Display All Students">
</form>
<div id="displayStudents"></div>


<h3>4-</h3>

<h3>5-</h3>

<h3>6-</h3>

<h3>7-</h3>

<h3>8- Get details of all the facilities in the system. </h3>
<form action="display-facilities-details.php">
<input type="submit" value="Display Facility Details">
</form>

<h3>9- Get details of all the employees currently working in a specific facility. </h3>
<form action="employees-specific-facility.php">
Facility ID: <input type="text" name="fid"><br>
OR <br>
Facility Name: <input type="text" name="fname"><br>
<input type="submit">
</form>

<h3>10- For a given employee, get the details of all the schedules they have been scheduled during a specific period of time.</h3>
<form action="schedules-specific-employee.php">
Employee Medicare Card Number: <input type="text" name="medicareCardNumber"><br>
Start Date: <input type="date" name="startTime"><br>
End Date: <input type="date" name="endTime"><br>
<input type="submit">
</form>

<h3>11- Get details of all the teachers who have been infected by COVID-19 in the past two weeks.</h3>
<form action="display-teachers-infected.php">
<input type="submit" value="Display Infected Teachers Details">
</form>

<h3>12- List the emails generated by a given facility.</h3>
<form action="emails-specific-facility.php">
Facility Name: <input type="text" name="fname"><br>
<input type="submit">
</form>

<h3>13- For a given facility, generate a list of all the teachers who have been on schedule to work in the last two weeks.</h3>
<form action="scheduledTeachers-specific-facility.php">
Facility Name: <input type="text" name="fname"><br>
<input type="submit">
</form>

<h3>14- For a given facility, give the total hours scheduled for every teacher during a specific period.</h3>
<form action="hoursScheduled-specific-facility.php">
Facility Name: <input type="text" name="fname"><br>
Starting Date: <input type="date" name="startTime"><br>
End Date: <input type="date" name="endTime"><br>
<input type="submit">
</form>

<h3>15- For every high school, provide the province where the school is located, the
school's name, the capacity of the school, and the total number of teachers in
the school who have been infected by COVID-19 in the past two weeks, and
the number of students in the school who have been infected by COVID-19 in
the past two weeks. </h3>
<form action="display-highschoolInfection-details.php"> 
<input type="submit" value="Display Highschool Infection Details">
</form>

<h3>16- For every ministry in the system, provide the minster's first-name, last-name,
the city of residence of the minister, and the total number of management
facilities, and the total number of educational facilities that the minister is
currently administering.</h3>
<form action="display-ministry-details.php"> 
<input type="submit" value="Display Ministry Details">
</form>

<h3>17- Get details of the counselor(s) who are currently working and has been infected by COVID-19 at least three times.</h3>
<form action="display-infectedCounselors-details.php"> 
<input type="submit" value="Display Counselors">
</form>

<hr> <!-- --------------------------------------------------->
sample crud operations (TO DELETE)

<h3>insert</h3>
<form action="insert-ex.php">
FirstName: <input type="text" name="firstname"><br>
LastName: <input type="text" name="lastname"><br>
E-mail: <input type="text" name="email"><br>
<input type="submit">
</form>

<br>
<br>
<h3>read</h3>
<form action="display-ex.php">
<input type="submit" value="Display Table">
</form>

<br>
<br>
<h3>update</h3>
<form action="update-ex.php">
FOR ID: <input type="text" name="id"><br>
FirstName: <input type="text" name="firstname"><br>
LastName: <input type="text" name="lastname"><br>
E-mail: <input type="text" name="email"><br>
<input type="submit">
</form>

<br>
<br>
<h3>delete</h3>
<form action="delete-ex.php">
FOR ID: <input type="text" name="id"><br>
<input type="submit">
<br>
<br>

</body>
</html>

<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "test";

try {
  $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
  // set the PDO error mode to exception
  $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
  echo "Connected successfully";
} catch(PDOException $e) {
  echo "Connection failed: " . $e->getMessage();
}




?>